Rentbuddy/Models/TouristPlace.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentbuddy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class TouristPlace
    {
        public int TouristPlace_ID { get; set; }

        [Required(ErrorMessage = "Please enter tourist place name")]
        [Display(Name = "Place Name")]
        public string TouristPlace_Name { get; set; }

        [Display(Name = "Place Image")]
        public string TouristPlace_Image { get; set; }

        [Required(ErrorMessage = "Please enter place description")]
        [Display(Name = "Description")]
        public string TouristPlace_Description { get; set; }

        [Required(ErrorMessage = "Please enter your address")]
        [Display(Name = "Location")]
        public string TouristPlace_Location { get; set; }

        [Required(ErrorMessage = "Please Enter Location Latutude")]
        [Display(Name = "Latitude")]
        public string TouuristPlace_Lat { get; set; }

        [Required(ErrorMessage = "Please enter location longitude")]
        [Display(Name = "Longitute")]
        public string TouristPlace_long { get; set; }

        public HttpPostedFileBase TouristImageFile { get; set; }
    }
}

Rentbuddy/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Rentbuddy.Models;

namespace Rentbuddy.Controllers
{
    public class AdminsController : Controller
    {
        private RentBuddyEntities db = new RentBuddyEntities();

        // GET: Admins
        public ActionResult Index()
        {
            return View(db.Admins.ToList());
        }

        // GET: Admins/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // GET: Admins/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Admin_ID,Admin_Name,Admin_Email,Admin_PhoneNO,Admin_Address,Admin_Password,Admin_Image")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Admins.Add(admin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(admin);
        }

        // GET: Admins/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // POST: Admins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Admin adm)
        {

            string fileName = Path.GetFileNameWithoutExtension(adm.AdminImageFile.FileName);
            string extension = Path.GetExtension(adm.AdminImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            adm.Admin_Image = "~/AdminImage/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/AdminImage/"), fileName);
            adm.AdminImageFile.SaveAs(fileName);

            if (ModelState.IsValid)
            {
                db.Entry(adm).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("AdminProfile");
            }
            return View(adm);
        }

        // GET: Admins/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }


        // POST: Admins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Admin admin = db.Admins.Find(id);
            db.Admins.Remove(admin);
            db.SaveChanges();
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index","Vehicles");

            
        }


















        [HttpGet]
        public ActionResult Signup()
        {
            return View();
        }



        [HttpPost]
        public ActionResult SignUp(Admin aust)
        {
            string fileName = Path.GetFileNameWithoutExtension(aust.AdminImageFile.FileName);
            string extension = Path.GetExtension(aust.AdminImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            aust.Admin_Image = "~/AdminImage/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/AdminImage/"), fileName);
            aust.AdminImageFile.SaveAs(fileName);

            if (ModelState.IsValid)
            {
                db.Admins.Add(aust);
                db.SaveChanges();
                ViewBag.Success = "successfully registered";
            }
            else
            {
                ViewBag.Failed = "Registration failed! Something went wrong! Please try again";
            }
            ModelState.Clear();
            return View();
        }





        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }



        [HttpPost]
        public ActionResult Login(TempAdmin tempAdmin)
        {
            if (ModelState.IsValid)
            {
                var admin = db.Admins.Where(c => c.Admin_Name.Equals(tempAdmin.Admin_Name)
                        && c.Admin_Email.Equals(tempAdmin.Admin_Email)
                        && c.Admin_Password.Equals(tempAdmin.Admin_Password)).FirstOrDefault();

                if (admin != null)
                {
                    FormsAuthentication.SetAuthCookie(tempAdmin.Admin_Name, false);
                    Session["AdminEmail"] = admin.Admin_Email;
                    Session["type"] = "Admin";
                    return RedirectToAction("AdminView");
                }
                else
                {
                    ViewBag.Failed = "Login Faild! Please try again";
                    return View();
                }
            }
            return View();
        }







        [HttpGet]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index", "Vehicles");
        }






        [HttpGet]
        public ActionResult AdminProfile()
        {
            String email = Convert.ToString(Session["AdminEmail"]);
            var admin = db.Admins.Where(u => u.Admin_Email.Equals(email)).FirstOrDefault();
            return View(admin);
        }



        public ActionResult AdminView()
        {
            return View();
        }


        public ActionResult AdminList()
        {
            return View(db.Admins.ToList());
        }







        public ActionResult AdminDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult AdminDeleteConfirmed(int id)
        {
            Admin admin = db.Admins.Find(id);
            db.Admins.Remove(admin);
            db.SaveChanges();
            return RedirectToAction("AdminList");
        }


        public ActionResult AllAdmin()
        {
            return View(db.Admins.ToList());
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rentbuddy/Controllers/TouristPlacesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Rentbuddy.Models;

namespace Rentbuddy.Controllers
{
    public class TouristPlacesController : Controller
    {
        private RentBuddyEntities db = new RentBuddyEntities();

        // GET: TouristPlaces
        public ActionResult Index()
        {
            return View(db.TouristPlaces.ToList());
        }

        // GET: TouristPlaces/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TouristPlace touristPlace = db.TouristPlaces.Find(id);
            if (touristPlace == null)
            {
                return HttpNotFound();
            }
            float x, y;

            x = float.Parse(touristPlace.TouuristPlace_Lat);
            ViewBag.lat = x;
            y = float.Parse(touristPlace.TouristPlace_long);
            ViewBag.lng = y;
            ViewBag.PlaceImage = touristPlace.TouristPlace_Image;
            return View(touristPlace);
        }

        // GET: TouristPlaces/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TouristPlaces/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TouristPlace_ID,TouristPlace_Name,TouristPlace_Image,TouristPlace_Description,TouristPlace_Location,TouuristPlace_Lat,TouristPlace_long")] TouristPlace touristPlace)
        {
            if (ModelState.IsValid)
            {
                db.TouristPlaces.Add(touristPlace);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(touristPlace);
        }

        // GET: TouristPlaces/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TouristPlace touristPlace = db.TouristPlaces.Find(id);
            if (touristPlace == null)
            {
                return HttpNotFound();
            }
            return View(touristPlace);
        }

        // POST: TouristPlaces/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TouristPlace tp)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tp).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("PlaceList");
            }
            return View(tp);
        }

        // GET: TouristPlaces/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TouristPlace touristPlace = db.TouristPlaces.Find(id);
            if (touristPlace == null)
            {
                return HttpNotFound();
            }
            return View(touristPlace);
        }

        // POST: TouristPlaces/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TouristPlace touristPlace = db.TouristPlaces.Find(id);
            db.TouristPlaces.Remove(touristPlace);
            db.SaveChanges();
            return RedirectToAction("PlaceList");
        }








        [HttpGet]
        public ActionResult PlaceList()
        {
            return View(db.TouristPlaces.ToList());
        }




        [HttpGet]
        public ActionResult AddPlace()
        {
            return View();
        }


        [HttpPost]
        public ActionResult AddPlace(TouristPlace tplace)
        {
            string fileName = Path.GetFileNameWithoutExtension(tplace.TouristImageFile.FileName);
            string extension = Path.GetExtension(tplace.TouristImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            tplace.TouristPlace_Image = "~/PlaceImage/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/PlaceImage/"), fileName);
            tplace.TouristImageFile.SaveAs(fileName);

            if (ModelState.IsValid)
            {
                db.TouristPlaces.Add(tplace);
                db.SaveChanges();
                ViewBag.Success = "successfully added";
            }
            else
            {
                ViewBag.Failed = "Added failed! Try Again";
            }
            ModelState.Clear();
            return View();
        }




        public ActionResult TouristPlace()
        {
            return View(db.TouristPlaces.ToList());
        }




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rentbuddy/Views/TouristPlaces/AddPlace.cshtml
@model Rentbuddy.Models.TouristPlace

@{
    ViewBag.Title = "AddPlace";
    var success = ViewBag.Success;
    var failed = ViewBag.Failed;
}

<link href="~/Content/placeadd.css" rel="stylesheet" />
<link href="~/Content/adminbutton.css" rel="stylesheet" />

<div class="containerX" style="margin-top:20px;">

    <a class="card1" href="@Url.Action("AdminView", "Admins")">
        <h3>Back To Home</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
    <a class="card1" href="@Url.Action("PlaceList", "TouristPlaces")">
        <h3>See All Place</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
</div>


@using (Html.BeginForm("AddPlace", "TouristPlaces", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()


    <div class="signup__container">
        <div class="container__child signup__thumbnail">
            <div class="thumbnail__content text-center">
                <h1 class="heading--primary">Welcome to MaxSoccer</h1>
                @if (success != null)
                {
                    <h2 style="color:#85F12B;">
                        @success
                    </h2>
                }
                else
                {
                    <h2 style="color:#85F12B;">
                        @failed
                    </h2>
                }
            </div>
        </div>
        <div class="container__child signup__form">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <label>Place Name</label>
                @Html.EditorFor(model => model.TouristPlace_Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "place name" } })
                @Html.ValidationMessageFor(model => model.TouristPlace_Name, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Place Photo</label>
                <input type="file" name="TouristImageFile" required />
            </div>
            <div class="form-group">
                <label>Place Description</label>
                @Html.EditorFor(model => model.TouristPlace_Description, new { htmlAttributes = new { @class = "form-control", @placeholder = "place description" } })
                @Html.ValidationMessageFor(model => model.TouristPlace_Description, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Place Location</label>
                @Html.EditorFor(model => model.TouristPlace_Location, new { htmlAttributes = new { @class = "form-control", @placeholder = "add location" } })
                @Html.ValidationMessageFor(model => model.TouristPlace_Location, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label>Latitude</label>
                @Html.EditorFor(model => model.TouuristPlace_Lat, new { htmlAttributes = new { @class = "form-control", @placeholder = "latitude" } })
                @Html.ValidationMessageFor(model => model.TouuristPlace_Lat, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label>Longitude</label>
                @Html.EditorFor(model => model.TouristPlace_long, new { htmlAttributes = new { @class = "form-control", @placeholder = "longitude" } })
                @Html.ValidationMessageFor(model => model.TouristPlace_long, "", new { @class = "text-danger" })
            </div>

            <div class="m-t-lg">
                <ul class="list-inline text-center">
                    <li>
                        <input type="submit" value="Add Place" class="btn btn--form" />
                    </li>
                </ul>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Rentbuddy/Views/TouristPlaces/Delete.cshtml
@model Rentbuddy.Models.TouristPlace

@{
    ViewBag.Title = "Delete";
}

<link href="~/Content/adminbutton.css" rel="stylesheet" />


<div class="containerX" style="margin-top:20px;">

    <a class="card1" href="@Url.Action("AdminView", "Admins")">
        <h3>Back To Home</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
    <a class="card1" href="@Url.Action("PlaceList", "TouristPlaces")">
        <h3>See All Place</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
</div>

<div>
    <h4>TouristPlace</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TouristPlace_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TouristPlace_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TouristPlace_Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TouristPlace_Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TouristPlace_Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TouristPlace_Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TouristPlace_Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TouristPlace_Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TouuristPlace_Lat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TouuristPlace_Lat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TouristPlace_long)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TouristPlace_long)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Rentbuddy/Views/TouristPlaces/Edit.cshtml
@model Rentbuddy.Models.TouristPlace

@{
    ViewBag.Title = "Edit";
}

<link href="~/Content/adminbutton.css" rel="stylesheet" />


<div class="containerX" style="margin-top:20px;">

    <a class="card1" href="@Url.Action("AdminView", "Admins")">
        <h3>Back To Home</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
    <a class="card1" href="@Url.Action("PlaceList", "TouristPlaces")">
        <h3>See All Place</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
</div>

@using (Html.BeginForm("Edit", "TouristPlaces", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TouristPlace</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TouristPlace_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.TouristPlace_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TouristPlace_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TouristPlace_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TouristPlace_Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TouristPlace_Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TouristPlace_Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TouristPlace_Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TouristPlace_Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TouristPlace_Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TouristPlace_Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TouristPlace_Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TouristPlace_Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TouuristPlace_Lat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TouuristPlace_Lat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TouuristPlace_Lat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TouristPlace_long, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TouristPlace_long, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TouristPlace_long, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Rentbuddy/Views/TouristPlaces/PlaceList.cshtml
@model IEnumerable<Rentbuddy.Models.TouristPlace>

@{
    ViewBag.Title = "PlaceList";
}

<link href="~/Content/team.css" rel="stylesheet" />
<link href="~/Content/adminbutton.css" rel="stylesheet" />

<div class="containerX" style="margin-top:20px;">

    <a class="card1" href="@Url.Action("AdminView", "Admins")">
        <h3>Back To Home</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
    <a class="card1" href="@Url.Action("AddPlace", "TouristPlaces")">
        <h3>Add New Place</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
</div>



<div class="tableX">
    <table class="containerD" style="width:1140px;">
        <thead>
            <tr>
                <th>
                    <h1 style="color: #3BFD0B; margin-left:40px; font-family: cursive; font-size: 20px;">
                        @Html.DisplayNameFor(model => model.TouristPlace_Name)
                    </h1>
                </th>
                <th>
                    <h1 style="color: #3BFD0B; margin-left:40px; font-family: cursive; font-size: 20px;">
                        @Html.DisplayNameFor(model => model.TouristPlace_Image)
                    </h1>
                </th>
                <th>
                    <h1 style="color: #3BFD0B; margin-left:40px; font-family: cursive; font-size: 20px;">
                        @Html.DisplayNameFor(model => model.TouristPlace_Description)
                    </h1>
                </th>
                <th>
                    <h1 style="color: #3BFD0B; font-family: cursive; font-size: 20px;">
                        @Html.DisplayNameFor(model => model.TouristPlace_Location)
                    </h1>
                </th>
                <th style="width: 180px;">
                    <h1 style="color: #3BFD0B; font-family:cursive; font-size:20px;">
                        Controll
                    </h1>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TouristPlace_Name)
                    </td>
                    <td>
                        @if (item.TouristPlace_Image != null)
                        {
                            var imgPath = item.TouristPlace_Image;
                            <img src="@Url.Content(imgPath)" alt="profile card" style="width:20%; height:20%;">
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TouristPlace_Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TouristPlace_Location)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.TouristPlace_ID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.TouristPlace_ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.TouristPlace_ID })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Rentbuddy/Views/TouristPlaces/TouristPlace.cshtml
@model IEnumerable<Rentbuddy.Models.TouristPlace>

@{
    ViewBag.Title = "TouristPlace";
}

<link href="~/Content/place.css" rel="stylesheet" />
<link href="~/Content/placeheader.css" rel="stylesheet" />

<h2 style="text-align:center; font-family:cursive; font-size: 40px; margin-top:20px;"></h2>

@foreach (var item in Model)
{
    <div class="flip-card-containerA" style="--hue: 220">
        <div class="flip-cardA">


            <div class="card-frontA">
                <figure>
                    <div class="img-bgA"></div>
                    <img src="@Url.Content(item.TouristPlace_Image)" alt="Profile Image">
                    <figcaption>@Html.DisplayFor(modelItem => item.TouristPlace_Name)</figcaption>
                </figure>

                <ul>
                </ul>
            </div>

            <div class="card-backA">
                <figure>
                    <div class="img-bgA"></div>
                    <img src="@Url.Content(item.TouristPlace_Image)" alt="Profile Image">
                </figure>

                <a href="@Url.Action("Details","TouristPlaces",new { id = item.TouristPlace_ID })">See Details</a>

                <div class="design-containerA">
                    <span class="designA design--1"></span>
                    <span class="designA design--2"></span>
                    <span class="designA design--3"></span>
                    <span class="designA design--4"></span>
                    <span class="designA design--5"></span>
                    <span class="designA design--6"></span>
                    <span class="designA design--7"></span>
                    <span class="designA design--8"></span>
                </div>
            </div>

        </div>
    </div>
}