Rentbuddy/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Rentbuddy.Models;

namespace Rentbuddy.Controllers
{
    public class AdminsController : Controller
    {
        private RentBuddyEntities db = new RentBuddyEntities();

        // GET: Admins
        public ActionResult Index()
        {
            return View(db.Admins.ToList());
        }

        // GET: Admins/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // GET: Admins/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Admin_ID,Admin_Name,Admin_Email,Admin_PhoneNO,Admin_Address,Admin_Password,Admin_Image")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Admins.Add(admin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(admin);
        }

        // GET: Admins/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // POST: Admins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Admin adm)
        {

            string fileName = Path.GetFileNameWithoutExtension(adm.AdminImageFile.FileName);
            string extension = Path.GetExtension(adm.AdminImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            adm.Admin_Image = "~/AdminImage/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/AdminImage/"), fileName);
            adm.AdminImageFile.SaveAs(fileName);

            if (ModelState.IsValid)
            {
                db.Entry(adm).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("AdminProfile");
            }
            return View(adm);
        }

        // GET: Admins/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }


        // POST: Admins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Admin admin = db.Admins.Find(id);
            db.Admins.Remove(admin);
            db.SaveChanges();
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index","Vehicles");

            
        }


















        [HttpGet]
        public ActionResult Signup()
        {
            return View();
        }



        [HttpPost]
        public ActionResult SignUp(Admin aust)
        {
            string fileName = Path.GetFileNameWithoutExtension(aust.AdminImageFile.FileName);
            string extension = Path.GetExtension(aust.AdminImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            aust.Admin_Image = "~/AdminImage/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/AdminImage/"), fileName);
            aust.AdminImageFile.SaveAs(fileName);

            if (ModelState.IsValid)
            {
                db.Admins.Add(aust);
                db.SaveChanges();
                ViewBag.Success = "successfully registered";
            }
            else
            {
                ViewBag.Failed = "Registration failed! Something went wrong! Please try again";
            }
            ModelState.Clear();
            return View();
        }





        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }



        [HttpPost]
        public ActionResult Login(TempAdmin tempAdmin)
        {
            if (ModelState.IsValid)
            {
                var admin = db.Admins.Where(c => c.Admin_Name.Equals(tempAdmin.Admin_Name)
                        && c.Admin_Email.Equals(tempAdmin.Admin_Email)
                        && c.Admin_Password.Equals(tempAdmin.Admin_Password)).FirstOrDefault();

                if (admin != null)
                {
                    FormsAuthentication.SetAuthCookie(tempAdmin.Admin_Name, false);
                    Session["AdminEmail"] = admin.Admin_Email;
                    Session["type"] = "Admin";
                    return RedirectToAction("AdminView");
                }
                else
                {
                    ViewBag.Failed = "Login Faild! Please try again";
                    return View();
                }
            }
            return View();
        }







        [HttpGet]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index", "Vehicles");
        }






        [HttpGet]
        public ActionResult AdminProfile()
        {
            String email = Convert.ToString(Session["AdminEmail"]);
            var admin = db.Admins.Where(u => u.Admin_Email.Equals(email)).FirstOrDefault();
            return View(admin);
        }



        public ActionResult AdminView()
        {
            return View();
        }


        public ActionResult AdminList()
        {
            return View(db.Admins.ToList());
        }







        public ActionResult AdminDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult AdminDeleteConfirmed(int id)
        {
            Admin admin = db.Admins.Find(id);
            db.Admins.Remove(admin);
            db.SaveChanges();
            return RedirectToAction("AdminList");
        }


        public ActionResult AllAdmin()
        {
            return View(db.Admins.ToList());
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rentbuddy/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Rentbuddy.Models;

namespace Rentbuddy.Controllers
{
    public class ContactUsController : Controller
    {
        private RentBuddyEntities db = new RentBuddyEntities();

        // GET: ContactUs
        public ActionResult Index()
        {
            return View(db.ContactUS.ToList());
        }

        // GET: ContactUs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactU contactU = db.ContactUS.Find(id);
            if (contactU == null)
            {
                return HttpNotFound();
            }
            return View(contactU);
        }

        // GET: ContactUs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ContactUs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ContactUS_ID,ContactUS_Name,ContactUS_PhoneNo,ContactUS_Email,ContactUS_Message")] ContactU contactU)
        {
            if (ModelState.IsValid)
            {
                db.ContactUS.Add(contactU);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(contactU);
        }

        // GET: ContactUs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactU contactU = db.ContactUS.Find(id);
            if (contactU == null)
            {
                return HttpNotFound();
            }
            return View(contactU);
        }

        // POST: ContactUs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ContactUS_ID,ContactUS_Name,ContactUS_PhoneNo,ContactUS_Email,ContactUS_Message")] ContactU contactU)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contactU).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contactU);
        }

        // GET: ContactUs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactU contactU = db.ContactUS.Find(id);
            if (contactU == null)
            {
                return HttpNotFound();
            }
            return View(contactU);
        }

        // POST: ContactUs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ContactU contactU = db.ContactUS.Find(id);
            db.ContactUS.Remove(contactU);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rentbuddy/Controllers/OrderMsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Rentbuddy.Models;

namespace Rentbuddy.Controllers
{
    public class OrderMsController : Controller
    {
        private RentBuddyEntities db = new RentBuddyEntities();

        // GET: OrderMs
        public ActionResult Index()
        {
            var orderMs = db.OrderMs.Include(o => o.Customer).Include(o => o.Vehicle);
            return View(orderMs.ToList());
        }

        // GET: OrderMs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderM orderM = db.OrderMs.Find(id);
            if (orderM == null)
            {
                return HttpNotFound();
            }
            return View(orderM);
        }

        // GET: OrderMs/Create
        public ActionResult Create()
        {
            ViewBag.Customer_ID = new SelectList(db.Customers, "Customer_ID", "Customer_Name");
            ViewBag.Vehicle_ID = new SelectList(db.Vehicles, "Vehicle_ID", "Vehicle_Name");
            return View();
        }

        // POST: OrderMs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Order_ID,Customer_ID,Vehicle_ID,Order_RentHour,Order_FromLocation,Order_ToLocation,Order_TotalPrice")] OrderM orderM)
        {
            if (ModelState.IsValid)
            {
                db.OrderMs.Add(orderM);
                db.SaveChanges();
                Session["OrderID"] = orderM.Order_ID;
                return RedirectToAction("PaymentView");
            }

            ViewBag.Customer_ID = new SelectList(db.Customers, "Customer_ID", "Customer_Name", orderM.Customer_ID);
            ViewBag.Vehicle_ID = new SelectList(db.Vehicles, "Vehicle_ID", "Vehicle_Name", orderM.Vehicle_ID);
            return View(orderM);
        }

        // GET: OrderMs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderM orderM = db.OrderMs.Find(id);
            if (orderM == null)
            {
                return HttpNotFound();
            }
            ViewBag.Customer_ID = new SelectList(db.Customers, "Customer_ID", "Customer_Name", orderM.Customer_ID);
            ViewBag.Vehicle_ID = new SelectList(db.Vehicles, "Vehicle_ID", "Vehicle_Name", orderM.Vehicle_ID);
            return View(orderM);
        }

        // POST: OrderMs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Order_ID,Customer_ID,Vehicle_ID,Order_RentHour,Order_FromLocation,Order_ToLocation,Order_TotalPrice")] OrderM orderM)
        {
            if (ModelState.IsValid)
            {
                db.Entry(orderM).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Customer_ID = new SelectList(db.Customers, "Customer_ID", "Customer_Name", orderM.Customer_ID);
            ViewBag.Vehicle_ID = new SelectList(db.Vehicles, "Vehicle_ID", "Vehicle_Name", orderM.Vehicle_ID);
            return View(orderM);
        }

        // GET: OrderMs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderM orderM = db.OrderMs.Find(id);
            if (orderM == null)
            {
                return HttpNotFound();
            }
            return View(orderM);
        }

        // POST: OrderMs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OrderM orderM = db.OrderMs.Find(id);
            db.OrderMs.Remove(orderM);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult PaymentView()
        {
            int oid = Convert.ToInt32(Session["OrderID"]);
            var order = db.OrderMs.Where(u => u.Order_ID.Equals(oid)).FirstOrDefault();

            return View(order);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rentbuddy/Views/Admins/AdminDelete.cshtml
@model Rentbuddy.Models.Admin

@{
    ViewBag.Title = "AdminDelete";
}

<link href="~/Content/adminbutton.css" rel="stylesheet" />


<div class="containerX" style="margin-top:20px;">
    <a class="card1" href="@Url.Action("AdminView", "Admins")">
        <h3>Back To Home</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
    <a class="card1" href="@Url.Action("AdminList", "Admins")">
        <h3>See All Admins</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
</div>
<div>
    <h4>Admin</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Admin_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Admin_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Admin_Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Admin_Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Admin_PhoneNO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Admin_PhoneNO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Admin_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Admin_Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Admin_Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Admin_Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Admin_Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Admin_Image)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>

Rentbuddy/Views/Admins/AdminList.cshtml
@model IEnumerable<Rentbuddy.Models.Admin>

@{
    ViewBag.Title = "AdminList";
}

<link href="~/Content/team.css" rel="stylesheet" />
<link href="~/Content/adminbutton.css" rel="stylesheet" />

<div class="containerX" style="margin-top:20px;">

    <a class="card1" href="@Url.Action("AdminView", "Admins")">
        <h3>Back To Home</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>

    <a class="card1" href="@Url.Action("Signup", "Admins")">
        <h3>Add New Admin</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
</div>

<div class="tableX">
    <table class="containerD" style="width:1140px;">
        <thead>
            <tr>
                <th>
                    <h1 style="color: #3BFD0B; margin-left:40px; font-family: cursive; font-size: 20px;">
                        @Html.DisplayNameFor(model => model.Admin_Name)
                    </h1>
                </th>
                <th>
                    <h1 style="color: #3BFD0B; margin-left:40px; font-family: cursive; font-size: 20px;">
                        @Html.DisplayNameFor(model => model.Admin_Email)
                    </h1>
                </th>
                <th>
                    <h1 style="color: #3BFD0B; margin-left:40px; font-family: cursive; font-size: 20px;">
                        @Html.DisplayNameFor(model => model.Admin_PhoneNO)
                    </h1>
                </th>
                <th>
                    <h1 style="color: #3BFD0B; margin-left:40px; font-family: cursive; font-size: 20px;">
                        @Html.DisplayNameFor(model => model.Admin_Address)
                    </h1>
                </th>
                <th>
                    <h1 style="color: #3BFD0B; font-family: cursive; font-size: 20px;">
                        @Html.DisplayNameFor(model => model.Admin_Image)
                    </h1>
                </th>
                <th style="width: 180px;">
                    <h1 style="color: #3BFD0B; font-family:cursive; font-size:20px;">
                        Controll
                    </h1>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Admin_Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Admin_Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Admin_PhoneNO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Admin_Address)
                    </td>
                    <td>
                        @if (item.Admin_Image != null)
                        {
                            var imgPath = item.Admin_Image;
                            <img src="@Url.Content(imgPath)" alt="profile card" style="width:20%; height:20%;">
                        }
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "AdminDelete", new { id = item.Admin_ID })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Rentbuddy/Views/Admins/AdminProfile.cshtml
@model Rentbuddy.Models.Admin

@{
    ViewBag.Title = "AdminProfile";
}

<link href="~/Content/profile.css" rel="stylesheet" />

<div class="wrapper">
    <div class="profile-card js-profile-card">
        <div class="profile-card__img">
            @if (Model.Admin_Image != null)
            {
                var imgPath = Model.Admin_Image;
                <img src="@Url.Content(imgPath)" alt="profile card">
            }
        </div>
        <div class="profile-card__cnt js-profile-cnt">
            <div class="profile-card__name">@Html.DisplayFor(model => model.Admin_Name)</div>
            <div class="profile-card__txt">@Html.DisplayFor(model => model.Admin_Email)</div>
            <div class="profile-card__txt">@Html.DisplayFor(model => model.Admin_PhoneNO)</div>
            <div class="profile-card-loc">
                <span class="profile-card-loc__txt">
                    @Html.DisplayFor(model => model.Admin_Address)
                </span>
            </div>
        </div>
        <div>
            <a href="@Url.Action("Edit", "Admins",new { id = Model.Admin_ID })" style="justify-content: center; text-align: center; float:left;">
                <h3 style="background: #5B0539; height: 30px; width: 100px; border-radius: 10px; color: #1FD809; padding-left: 4px;">
                    Edit
                </h3>
            </a>
            <a href="@Url.Action("Delete", "Admins",new { id = Model.Admin_ID })" style="justify-content: center; text-align: center; float:right;">
                <h3 style="background: #5B0539; height: 30px; width: 100px; border-radius: 10px; color: #1FD809;">
                    Delete
                </h3>
            </a>
        </div>
    </div>
</div>

Rentbuddy/Views/Admins/AdminView.cshtml
@{
    ViewBag.Title = "AdminView";
}

<link href="~/Content/adminview.css" rel="stylesheet" />

<div class="containerX" style="margin-top:40px;">

    <a class="card1" href="@Url.Action("CategoryList", "Categories")">
        <h3>Category Management</h3>
        <ul class="small">
            <li>Add Category</li>
            <li>Category Details</li>
            <li>See All Category</li>
            <li>Update Category</li>
        </ul>
        <div class="dimmer"></div>
        <div class="go-corner" href="#">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>

    <a class="card1" href="@Url.Action("AllVehicle", "Vehicles")">
        <h3>Vehicle Management</h3>
        <ul class="small">
            <li>Vehicle Details</li>
            <li>Edit Vehicle Information</li>
            <li>Add New Vehicle</li>
            <li>Remove Current Vehicle</li>
        </ul>
        <div class="go-corner" href="#">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>

    <a class="card1" href="@Url.Action("CustomerList", "Customers")">
        <h3>Customer Management</h3>
        <ul class="small">
            <li>Customer Details</li>
            <li>Edit Vehicle History</li>
            <li>Customer's Order Approval</li>
            <li>Banned Current Customer</li>
        </ul>
        <div class="go-corner" href="#">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>

    <a class="card1" href="@Url.Action("AdminList", "Admins")">
        <h3>Admin Management</h3>
        <ul class="small">
            <li>Admin Details</li>
            <li>Edit Admin's Informations</li>
            <li>Add New Admin</li>
            <li>Remove Current Admin</li>
        </ul>
        <div class="dimmer"></div>
        <div class="go-corner" href="#">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>

    <a class="card1" href="@Url.Action("Index", "OrderMs")">
        <h3>Order Management</h3>
        <ul class="small">
            <li>Order Details</li>
            <li>Edit Order Information</li>
            <li>New Order Approval</li>
        </ul>
        <div class="dimmer"></div>
        <div class="go-corner" href="#">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>

    <a class="card1" href="@Url.Action("PlaceList", "TouristPlaces")">
        <h3>Tourist Place</h3>
        <ul class="small">
            <li>Tourist place Details</li>
            <li>Add New Tourist Place</li>
            <li>Add New Vehicle</li>
        </ul>
        <div class="dimmer"></div>
        <div class="go-corner" href="#">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
    <a class="card1" href="@Url.Action("Index", "ContactUs")">
        <h3>Contact Management</h3>
        <ul class="small">
            <li>Contact Us Details</li>
            <li>See Customers Review</li>
            <li>Give Customer Feedback</li>
        </ul>
        <div class="dimmer"></div>
        <div class="go-corner" href="#">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>

</div>

Rentbuddy/Views/Admins/Delete.cshtml
@model Rentbuddy.Models.Admin

@{
    ViewBag.Title = "Delete";
}

<link href="~/Content/profile.css" rel="stylesheet" />

<div class="wrapper">
    <div class="profile-card js-profile-card">
        <div class="profile-card__img">
            @if (Model.Admin_Image != null)
            {
                var imgPath = Model.Admin_Image;
                <img src="@Url.Content(imgPath)" alt="profile card">
            }
        </div>

        <div class="profile-card__cnt js-profile-cnt">
            <div class="profile-card__name">@Html.DisplayFor(model => model.Admin_Name)</div>
            <div class="profile-card__txt">@Html.DisplayFor(model => model.Admin_Email)</div>
            <div class="profile-card__txt">@Html.DisplayFor(model => model.Admin_PhoneNO)</div>
            <div class="profile-card__txt">@Html.DisplayFor(model => model.Admin_Address)</div>
        </div>

        <h3 style="text-align:center; color: #00ff21; margin-top: -20px;">Are you sure you want to delete this profile?</h3>


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="m-t-lg">
                <ul class="list-inline text-center">
                    <li>
                        <input type="submit" value="Delete" class="btn btn-default" />
                    </li>
                </ul>
            </div>
        }

    </div>
</div>

Rentbuddy/Views/Admins/Edit.cshtml
@model Rentbuddy.Models.Admin

@{
    ViewBag.Title = "Edit";
}

<link href="~/Content/profile.css" rel="stylesheet" />

@using (Html.BeginForm("Edit", "Admins", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="wrapper">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Admin_ID)
        <div class="profile-card js-profile-card">
            <div class="profile-card__img">
                @if (Model.Admin_Image != null)
                {
                    var imgPath = Model.Admin_Image;
                    <img src="@Url.Content(imgPath)" alt="profile card">
                }
            </div>

            <div class="profile-card__cnt js-profile-cnt">

                <div class="profile-card__txt">
                    <label>Name</label>
                    @Html.EditorFor(model => model.Admin_Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Admin_Name, "", new { @class = "text-danger" })
                </div>

                <div class="profile-card__txt">
                    <label>Email</label>
                    @Html.EditorFor(model => model.Admin_Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Admin_Email, "", new { @class = "text-danger" })
                </div>

                <div class="profile-card__txt">
                    <label>Phone No</label>
                    @Html.EditorFor(model => model.Admin_PhoneNO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Admin_PhoneNO, "", new { @class = "text-danger" })
                </div>

                <div class="profile-card__txt">
                    <label>Address</label>
                    @Html.EditorFor(model => model.Admin_Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Admin_Address, "", new { @class = "text-danger" })
                </div>

                <div class="profile-card__txt">
                    <label>Password</label>
                    @Html.EditorFor(model => model.Admin_Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Admin_Password, "", new { @class = "text-danger" })
                </div>


                <div class="profile-card__txt">
                    <label>Profile Pic</label>
                    <input type="file" name="AdminImageFile" />
                </div>

                <div class="m-t-lg">
                    <ul class="list-inline text-center">
                        <li>
                            <input type="submit" value="Save" class="btn btn--form" />
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}