Rentbuddy/Models/Category.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentbuddy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Vehicles = new HashSet<Vehicle>();
        }

        public int Category_ID { get; set; }

        [Required(ErrorMessage = "Please enter category name!")]
        [Display(Name = "Category Name")]
        public string Category_Name { get; set; }

        [Display(Name = "Category Image")]
        public string Category_Image { get; set; }

        public HttpPostedFileBase CategoryImageFile { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}

Rentbuddy/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Rentbuddy.Models;

namespace Rentbuddy.Controllers
{
    public class AdminsController : Controller
    {
        private RentBuddyEntities db = new RentBuddyEntities();

        // GET: Admins
        public ActionResult Index()
        {
            return View(db.Admins.ToList());
        }

        // GET: Admins/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // GET: Admins/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Admin_ID,Admin_Name,Admin_Email,Admin_PhoneNO,Admin_Address,Admin_Password,Admin_Image")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Admins.Add(admin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(admin);
        }

        // GET: Admins/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // POST: Admins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Admin adm)
        {

            string fileName = Path.GetFileNameWithoutExtension(adm.AdminImageFile.FileName);
            string extension = Path.GetExtension(adm.AdminImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            adm.Admin_Image = "~/AdminImage/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/AdminImage/"), fileName);
            adm.AdminImageFile.SaveAs(fileName);

            if (ModelState.IsValid)
            {
                db.Entry(adm).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("AdminProfile");
            }
            return View(adm);
        }

        // GET: Admins/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }


        // POST: Admins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Admin admin = db.Admins.Find(id);
            db.Admins.Remove(admin);
            db.SaveChanges();
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index","Vehicles");

            
        }


















        [HttpGet]
        public ActionResult Signup()
        {
            return View();
        }



        [HttpPost]
        public ActionResult SignUp(Admin aust)
        {
            string fileName = Path.GetFileNameWithoutExtension(aust.AdminImageFile.FileName);
            string extension = Path.GetExtension(aust.AdminImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            aust.Admin_Image = "~/AdminImage/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/AdminImage/"), fileName);
            aust.AdminImageFile.SaveAs(fileName);

            if (ModelState.IsValid)
            {
                db.Admins.Add(aust);
                db.SaveChanges();
                ViewBag.Success = "successfully registered";
            }
            else
            {
                ViewBag.Failed = "Registration failed! Something went wrong! Please try again";
            }
            ModelState.Clear();
            return View();
        }





        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }



        [HttpPost]
        public ActionResult Login(TempAdmin tempAdmin)
        {
            if (ModelState.IsValid)
            {
                var admin = db.Admins.Where(c => c.Admin_Name.Equals(tempAdmin.Admin_Name)
                        && c.Admin_Email.Equals(tempAdmin.Admin_Email)
                        && c.Admin_Password.Equals(tempAdmin.Admin_Password)).FirstOrDefault();

                if (admin != null)
                {
                    FormsAuthentication.SetAuthCookie(tempAdmin.Admin_Name, false);
                    Session["AdminEmail"] = admin.Admin_Email;
                    Session["type"] = "Admin";
                    return RedirectToAction("AdminView");
                }
                else
                {
                    ViewBag.Failed = "Login Faild! Please try again";
                    return View();
                }
            }
            return View();
        }







        [HttpGet]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index", "Vehicles");
        }






        [HttpGet]
        public ActionResult AdminProfile()
        {
            String email = Convert.ToString(Session["AdminEmail"]);
            var admin = db.Admins.Where(u => u.Admin_Email.Equals(email)).FirstOrDefault();
            return View(admin);
        }



        public ActionResult AdminView()
        {
            return View();
        }


        public ActionResult AdminList()
        {
            return View(db.Admins.ToList());
        }







        public ActionResult AdminDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult AdminDeleteConfirmed(int id)
        {
            Admin admin = db.Admins.Find(id);
            db.Admins.Remove(admin);
            db.SaveChanges();
            return RedirectToAction("AdminList");
        }


        public ActionResult AllAdmin()
        {
            return View(db.Admins.ToList());
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rentbuddy/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Rentbuddy.Models;

namespace Rentbuddy.Controllers
{
    public class CategoriesController : Controller
    {
        private RentBuddyEntities db = new RentBuddyEntities();

        // GET: Categories
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Category_ID,Category_Name,Category_Image")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Category cata)
        {
            string fileName = Path.GetFileNameWithoutExtension(cata.CategoryImageFile.FileName);
            string extension = Path.GetExtension(cata.CategoryImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            cata.Category_Image = "~/CategoryImage/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/CategoryImage/"), fileName);
            cata.CategoryImageFile.SaveAs(fileName);

            if (ModelState.IsValid)
            {
                db.Entry(cata).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("CategoryList");
            }
            return View(cata);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("CategoryList");
        }





        public ActionResult CategoryList()
        {
            return View(db.Categories.ToList());
        }



        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }


        [HttpPost]
        public ActionResult AddCategory(Category cat)
        {
            string fileName = Path.GetFileNameWithoutExtension(cat.CategoryImageFile.FileName);
            string extension = Path.GetExtension(cat.CategoryImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            cat.Category_Image = "~/CategoryImage/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/CategoryImage/"), fileName);
            cat.CategoryImageFile.SaveAs(fileName);

            if (ModelState.IsValid)
            {
                db.Categories.Add(cat);
                db.SaveChanges();
                ViewBag.Success = "Successfully added";
            }
            else
            {
                ViewBag.Failed = "Something went wrong! PLease try again";
            }
            ModelState.Clear();
            return View();
        }




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rentbuddy/Views/Categories/AddCategory.cshtml
@model Rentbuddy.Models.Category

@{
    ViewBag.Title = "AddCategory";
    var success = ViewBag.Success;
    var failed = ViewBag.Failed;
}

<link href="~/Content/placeadd.css" rel="stylesheet" />
<link href="~/Content/adminbutton.css" rel="stylesheet" />


<div class="containerX" style="margin-top:20px;">

    <a class="card1" href="@Url.Action("AdminView", "Admins")">
        <h3>Back To Home</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
    <a class="card1" href="@Url.Action("CategoryList", "Categories")">
        <h3>See All Category</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
</div>


@using (Html.BeginForm("AddCategory", "Categories", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="signup__container">
        <div class="container__child signup__thumbnail">
            <div class="thumbnail__content text-center">
                <h1 class="heading--primary">Welcome to RentBuddy</h1>
                @if (success != null)
                {
                    <h2 style="color:#85F12B;">
                        @success
                    </h2>
                }
                else
                {
                    <h2 style="color:#85F12B;">
                        @failed
                    </h2>
                }
            </div>
        </div>
        <div class="container__child signup__form">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <label>Category Name</label>
                @Html.EditorFor(model => model.Category_Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "category name" } })
                @Html.ValidationMessageFor(model => model.Category_Name, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label>Category Photo</label>
                <input type="file" name="CategoryImageFile" required />
            </div>

            <div class="m-t-lg">
                <ul class="list-inline text-center">
                    <li>
                        <input type="submit" value="Add Category" class="btn btn--form" />
                    </li>
                </ul>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Rentbuddy/Views/Categories/CategoryList.cshtml
@model IEnumerable<Rentbuddy.Models.Category>

@{
    ViewBag.Title = "CategoryList";
}

<link href="~/Content/team.css" rel="stylesheet" />
<link href="~/Content/adminbutton.css" rel="stylesheet" />

<div class="containerX" style="margin-top:20px;">

    <a class="card1" href="@Url.Action("AdminView", "Admins")">
        <h3>Back To Home</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
    <a class="card1" href="@Url.Action("AddCategory", "Categories")">
        <h3>Add New Category</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
</div>



<div class="tableX">
    <table class="containerD" style="width:1140px;">
        <thead>
            <tr>
                <th>
                    <h1 style="color: #3BFD0B; margin-left:40px; font-family: cursive; font-size: 20px;">
                        @Html.DisplayNameFor(model => model.Category_Name)
                    </h1>
                </th>
                <th>
                    <h1 style="color: #3BFD0B; margin-left:40px; font-family: cursive; font-size: 20px;">
                        @Html.DisplayNameFor(model => model.Category_Image)
                    </h1>
                </th>
                <th style="width: 180px;">
                    <h1 style="color: #3BFD0B; font-family:cursive; font-size:20px;">
                        Controll
                    </h1>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category_Name)
                    </td>
                    <td>
                        @if (item.Category_Image != null)
                        {
                            var imgPath = item.Category_Image;
                            <img src="@Url.Content(imgPath)" alt="profile card" style="width:20%; height:20%;">
                        }
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Category_ID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Category_ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Category_ID })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Rentbuddy/Views/Categories/Create.cshtml
@model Rentbuddy.Models.Category

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Category_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category_Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category_Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category_Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Rentbuddy/Views/Categories/Delete.cshtml
@model Rentbuddy.Models.Category

@{
    ViewBag.Title = "Delete";
}

<link href="~/Content/placeadd.css" rel="stylesheet" />
<link href="~/Content/adminbutton.css" rel="stylesheet" />


<div class="containerX" style="margin-top:20px;">

    <a class="card1" href="@Url.Action("AdminView", "Admins")">
        <h3>Back To Home</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
    <a class="card1" href="@Url.Action("CategoryList", "Categories")">
        <h3>See All Category</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
</div>
<hr />
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Category_Name)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Category_Name)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Category_Image)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Category_Image)
    </dd>

</dl>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" />
    </div>
}
</div>

Rentbuddy/Views/Categories/Details.cshtml
@model Rentbuddy.Models.Category

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category_Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category_Image)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Category_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Rentbuddy/Views/Categories/Edit.cshtml
@model Rentbuddy.Models.Category

@{
    ViewBag.Title = "Edit";
}




<link href="~/Content/placeadd.css" rel="stylesheet" />
<link href="~/Content/adminbutton.css" rel="stylesheet" />


<div class="containerX" style="margin-top:20px;">

    <a class="card1" href="@Url.Action("AdminView", "Admins")">
        <h3>Back To Home</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
    <a class="card1" href="@Url.Action("CategoryList", "Categories")">
        <h3>See All Category</h3>
        <div class="go-corner">
            <div class="go-arrow">
                →
            </div>
        </div>
    </a>
</div>

@using (Html.BeginForm("Edit", "Categories", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Category_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Category_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category_Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="CategoryImageFile" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Rentbuddy/Views/Categories/Index.cshtml
@model IEnumerable<Rentbuddy.Models.Category>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Category_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category_Image)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Category_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category_Image)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Category_ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.Category_ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Category_ID })
        </td>
    </tr>
}

</table>